import { StyleSheet } from "react-native";
import { ACCENT, ACCENT_BORDER, ACCENT_MUTED, CARD_BG, CARD_BORDER, CARD_W, NODE_RADIUS, STAT_BAR_W, STAT_LABEL_W, STAT_PCT_W, TEXT_DARK, TEXT_MID, TEXT_MUTED, ACCENT_LIGHT } from "./constants";

export const s = StyleSheet.create({
  overlay: { flex: 1 },
  scroll: { flex: 1 },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 50 },
  revealScrollContent: { paddingHorizontal: 18, paddingBottom: 50, alignItems: "center" },

  blob1: { position: "absolute", width: 260, height: 260, borderRadius: 130, backgroundColor: "rgba(155,138,208,0.14)", top: -60, right: -60 },
  blob2: { position: "absolute", width: 200, height: 200, borderRadius: 100, backgroundColor: "rgba(120,144,200,0.1)", bottom: 80, left: -60 },

  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 16, paddingTop: 54, paddingBottom: 10, zIndex: 20 },
  backBtn: { flexDirection: "row", alignItems: "center", gap: 6, paddingVertical: 6, paddingHorizontal: 2 },
  backTxt: { fontSize: 13, fontFamily: "Poppins-Medium", color: TEXT_MUTED },
  closeBtn: { paddingVertical: 6, paddingHorizontal: 4 },
  closeTxt: { fontSize: 17, color: TEXT_MUTED, fontFamily: "Poppins-Regular" },

  introBadge: { alignSelf: "flex-start", backgroundColor: ACCENT_MUTED, borderRadius: 20, paddingHorizontal: 10, paddingVertical: 4, marginBottom: 14, marginTop: 6, borderWidth: 1, borderColor: ACCENT_BORDER },
  introBadgeTxt: { fontSize: 8, fontFamily: "Poppins-SemiBold", letterSpacing: 2, color: ACCENT },
  heroTitle: { fontSize: 27, fontFamily: "Playfair-ExtraBold", color: TEXT_DARK, marginBottom: 6, lineHeight: 35 },
  heroSub: { fontSize: 13, fontFamily: "Poppins-Regular", color: TEXT_MUTED, marginBottom: 24, lineHeight: 20 },

  introAuthorCard: { backgroundColor: CARD_BG, borderRadius: 14, padding: 14, marginBottom: 16, borderWidth: 1, borderColor: CARD_BORDER, overflow: "hidden", shadowColor: ACCENT, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 8, elevation: 2 },
  introAuthorAccent: { position: "absolute", left: 0, top: 0, bottom: 0, width: 3, backgroundColor: ACCENT, borderRadius: 2 },
  introAuthorName: { fontSize: 14, fontFamily: "Poppins-SemiBold", color: TEXT_DARK, marginBottom: 3, paddingLeft: 10 },
  introAuthorRole: { fontSize: 11, fontFamily: "Poppins-Regular", color: ACCENT_LIGHT, paddingLeft: 10, lineHeight: 17 },

  introBody: { fontSize: 14, fontFamily: "Poppins-Regular", color: TEXT_MID, lineHeight: 22, marginBottom: 16 },
  introBodyAlt: { fontSize: 13, fontFamily: "Poppins-Regular", color: TEXT_MID, lineHeight: 20 },
  introQuoteBox: { backgroundColor: ACCENT_MUTED, borderRadius: 14, padding: 16, marginBottom: 14, borderWidth: 1, borderColor: ACCENT_BORDER },
  introQuoteMark: { fontSize: 30, fontFamily: "Playfair-ExtraBold", color: ACCENT, lineHeight: 26, marginBottom: 4 },
  introQuoteTxt: { fontSize: 14, fontFamily: "Playfair-ExtraBold", color: TEXT_DARK, lineHeight: 22, fontStyle: "italic", marginBottom: 8 },
  introQuoteAuthor: { fontSize: 11, fontFamily: "Poppins-Regular", color: ACCENT, textAlign: "right" },
  introIkigaiBox: { backgroundColor: "rgba(120,144,168,0.08)", borderRadius: 14, padding: 14, marginBottom: 14, borderWidth: 1, borderColor: "rgba(120,144,168,0.16)", gap: 6 },
  introMechanicBox: { backgroundColor: "rgba(120,144,168,0.08)", borderRadius: 14, padding: 14, marginBottom: 20, borderWidth: 1, borderColor: "rgba(120,144,168,0.16)", gap: 6 },
  introSectionLabel: { fontSize: 9, fontFamily: "Poppins-SemiBold", letterSpacing: 2, color: TEXT_MUTED },
  introCta: { flexDirection: "row", alignItems: "center", justifyContent: "center", backgroundColor: ACCENT, borderRadius: 28, paddingVertical: 14, gap: 8, marginBottom: 20, shadowColor: ACCENT, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 10, elevation: 5 },
  introCtaTxt: { fontSize: 14, fontFamily: "Poppins-SemiBold", color: "#fff", letterSpacing: 0.3 },

  selectCard: { backgroundColor: CARD_BG, borderRadius: 18, padding: 18, marginBottom: 14, borderWidth: 1, borderColor: CARD_BORDER, overflow: "hidden", shadowColor: ACCENT, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 8, elevation: 2 },
  selectCardDone: { borderColor: "rgba(107,90,158,0.45)", backgroundColor: "rgba(107,90,158,0.06)" },
  selectCardAccent: { position: "absolute", left: 0, top: 0, bottom: 0, width: 3, backgroundColor: ACCENT, borderRadius: 2 },
  selectCardAccentDone: { backgroundColor: "#4CAF82" },
  selectCardTitle: { fontSize: 17, fontFamily: "Playfair-ExtraBold", color: TEXT_DARK, marginBottom: 4, paddingLeft: 10 },
  selectCardSub: { fontSize: 12, fontFamily: "Poppins-Regular", color: TEXT_MUTED, paddingLeft: 10 },
  selectCardCheckBadge: { position: "absolute", top: 12, right: 12, width: 20, height: 20, borderRadius: 10, backgroundColor: "#4CAF82", alignItems: "center", justifyContent: "center" },

  compassContainer: { flex: 1 },
  compassHeader: { alignItems: "center", paddingTop: 4, paddingBottom: 8, paddingHorizontal: 20 },
  compassTitle: { fontSize: 19, fontFamily: "Playfair-ExtraBold", color: TEXT_DARK, marginBottom: 4, textAlign: "center" },
  compassSub: { fontSize: 12, fontFamily: "Poppins-Regular", color: TEXT_MUTED, textAlign: "center" },
  targetRing: { position: "absolute", width: 112, height: 112, borderRadius: 56, borderWidth: 1.5, borderColor: ACCENT, backgroundColor: "transparent" },
  targetDot: { position: "absolute", width: 10, height: 10, borderRadius: 5, backgroundColor: "rgba(107,90,158,0.6)" },
  progressRow: { position: "absolute", left: 0, right: 0, flexDirection: "row", justifyContent: "center", gap: 8 },
  progressDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: "rgba(107,90,158,0.15)", borderWidth: 1, borderColor: "rgba(107,90,158,0.3)" },
  progressDotActive: { backgroundColor: ACCENT, borderColor: ACCENT },
  burst: { position: "absolute", width: 160, height: 160, borderRadius: 80, backgroundColor: "rgba(139,122,184,0.25)", zIndex: 5 },
  nodeGlow: { position: "absolute", width: NODE_RADIUS * 2 + 18, height: NODE_RADIUS * 2 + 18, borderRadius: NODE_RADIUS + 9, left: -9, top: -9 },
  nodeBorder: { width: NODE_RADIUS * 2, height: NODE_RADIUS * 2, borderRadius: NODE_RADIUS, borderWidth: 1.5, overflow: "hidden", shadowColor: ACCENT, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 4 },
  node: { width: "100%", height: "100%", alignItems: "center", justifyContent: "center" },
  nodeLabel: { fontSize: 9, fontFamily: "Poppins-SemiBold", color: TEXT_MID, textAlign: "center", marginTop: 5, width: NODE_RADIUS * 2 + 10, letterSpacing: 0.3 },

  collectCard: { width: CARD_W, borderRadius: 22, padding: 18, marginBottom: 18, elevation: 0, shadowOpacity: 0 },
  cardSheen: { ...StyleSheet.absoluteFillObject, borderRadius: 22 },
  cardTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 14 },
  cardBadge: { backgroundColor: "rgba(104,153,180,0.22)", borderRadius: 10, paddingHorizontal: 8, paddingVertical: 3, borderWidth: 1, borderColor: "rgba(104,153,180,0.4)" },
  cardBadgeTxt: { fontSize: 7, fontFamily: "Poppins-SemiBold", letterSpacing: 1.5, color: "rgba(168,210,235,0.95)" },
  cardIconArea: { alignItems: "center", justifyContent: "center", marginBottom: 12, height: 60 },
  cardIconRing: { position: "absolute", width: 56, height: 56, borderRadius: 28, borderWidth: 1, borderColor: "rgba(104,153,180,0.45)", overflow: "hidden" },
  cardTitle: { fontSize: 20, fontFamily: "Playfair-ExtraBold", color: "#E8F4FA", textAlign: "center", marginBottom: 4, lineHeight: 26 },
  cardSubtitle: { fontSize: 10, fontFamily: "Poppins-Regular", color: "rgba(168,200,220,0.75)", textAlign: "center", marginBottom: 14, letterSpacing: 0.3 },
  cardDivider: { height: 1, backgroundColor: "rgba(104,153,180,0.3)", marginBottom: 12 },
  statRow: { flexDirection: "row", alignItems: "center", marginBottom: 8, gap: 8 },
  statLabel: { fontSize: 10, fontFamily: "Poppins-Medium", color: "rgba(168,200,220,0.85)", width: STAT_LABEL_W },
  statTrack: { flex: 1, height: 6, borderRadius: 3, backgroundColor: "rgba(255,255,255,0.1)", overflow: "hidden" },
  statFill: { height: "100%", borderRadius: 3, backgroundColor: "#6899B4" },
  statPct: { fontSize: 10, fontFamily: "Poppins-SemiBold", color: "rgba(168,210,235,0.9)", width: STAT_PCT_W, textAlign: "right" },

  reflectionCard: { backgroundColor: CARD_BG, borderRadius: 20, padding: 20, marginBottom: 14, borderWidth: 1, borderColor: CARD_BORDER, overflow: "hidden", width: "100%", shadowColor: ACCENT, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 10, elevation: 3 },
  reflectionAccent: { position: "absolute", left: 0, top: 0, bottom: 0, width: 4, backgroundColor: ACCENT, borderRadius: 2 },
  revealQuote: { fontSize: 14, fontFamily: "Playfair-ExtraBold", color: TEXT_DARK, fontStyle: "italic", lineHeight: 22, marginBottom: 14 },
  revealDivider: { height: 1, backgroundColor: "rgba(107,90,158,0.15)", marginBottom: 14 },
  reflectionLabel: { fontSize: 8, fontFamily: "Poppins-SemiBold", letterSpacing: 2, color: ACCENT, marginBottom: 8 },
  reflectionTxt: { fontSize: 13, fontFamily: "Poppins-Regular", color: TEXT_MID, lineHeight: 21 },

  zenCard: { backgroundColor: "rgba(107,90,158,0.07)", borderRadius: 20, padding: 20, marginBottom: 20, borderWidth: 1, borderColor: ACCENT_BORDER, overflow: "hidden", width: "100%" },
  zenAccent: { position: "absolute", left: 0, top: 0, bottom: 0, width: 4, backgroundColor: ACCENT, borderRadius: 2 },
  zenLabel: { fontSize: 8, fontFamily: "Poppins-SemiBold", letterSpacing: 2, color: ACCENT, marginBottom: 8 },
  zenTxt: { fontSize: 13, fontFamily: "Poppins-Medium", color: TEXT_MID, lineHeight: 21 },

  actionsRow: { flexDirection: "row", gap: 10, marginBottom: 30, width: "100%" },
  actionBtn: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, backgroundColor: ACCENT, borderRadius: 24, paddingVertical: 13, shadowColor: ACCENT, shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 4 },
  actionBtnAlt: { backgroundColor: "#7890A8", shadowColor: "#7890A8" },
  actionBtnSuccess: { backgroundColor: "#4CAF82", shadowColor: "#4CAF82" },
  actionBtnTxt: { fontSize: 13, fontFamily: "Poppins-SemiBold", color: "#fff" },
});
